// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatisfactorySmartHub.Infrastructure.Persistance.Repositories;

#nullable disable

namespace SatisfactorySmartHub.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241021201958_AddProcessStep")]
    partial class AddProcessStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CorporationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ClockSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("MachineryConfigItem");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Corporation", "Corporation")
                        .WithMany("Branches")
                        .HasForeignKey("CorporationId");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.ProcessStep", "ProcessStep")
                        .WithMany("ImplementedMachinery")
                        .HasForeignKey("ProcessStepId");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Branch", "Branch")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("BranchId");

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.OwnsOne("SatisfactorySmartHub.Domain.Entities.ItemWithAmount", "Target", b1 =>
                        {
                            b1.Property<Guid>("ProcessStepId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ItemId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ProcessStepId");

                            b1.ToTable("ProcessStep");

                            b1.WithOwner()
                                .HasForeignKey("ProcessStepId");
                        });

                    b.Navigation("Branch");

                    b.Navigation("Recipe");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ProcessSteps");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Navigation("ImplementedMachinery");
                });
#pragma warning restore 612, 618
        }
    }
}
