// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatisfactorySmartHub.Infrastructure.Persistance.Repositories;

#nullable disable

namespace SatisfactorySmartHub.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241111181839_AddStaticData1111241918")]
    partial class AddStaticData1111241918
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CorporationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ByProduct", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ByProducts");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("6b95911b-3711-470a-84ff-f843825eb3e6"),
                            ItemId = new Guid("6c944ca5-c6ba-4df4-a08e-c06134ba1472"),
                            Amount = 1m
                        },
                        new
                        {
                            RecipeId = new Guid("34f401c1-1fbf-4d31-aff2-f04fa40f1831"),
                            ItemId = new Guid("be5c74ec-52aa-400c-a1b4-3fd3ac9a5ee5"),
                            Amount = 3m
                        });
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c944ca5-c6ba-4df4-a08e-c06134ba1472"),
                            Name = "Iron Ore"
                        },
                        new
                        {
                            Id = new Guid("be5c74ec-52aa-400c-a1b4-3fd3ac9a5ee5"),
                            Name = "Iron Ingot"
                        },
                        new
                        {
                            Id = new Guid("bb7bde8d-b9ce-4d68-a852-b16e621fa3a6"),
                            Name = "Iron Plate"
                        });
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerConsumption")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("629893a3-3ae2-408f-8af5-70bcea9c1d19"),
                            Name = "Smelter",
                            PowerConsumption = 4
                        },
                        new
                        {
                            Id = new Guid("9a874da3-3ea4-427d-8552-fc26dccba215"),
                            Name = "Constructor",
                            PowerConsumption = 4
                        });
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ClockSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("MachineConfigItems");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MainProduct", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("MainProducts");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("6b95911b-3711-470a-84ff-f843825eb3e6"),
                            ItemId = new Guid("be5c74ec-52aa-400c-a1b4-3fd3ac9a5ee5"),
                            Amount = 1m
                        },
                        new
                        {
                            RecipeId = new Guid("34f401c1-1fbf-4d31-aff2-f04fa40f1831"),
                            ItemId = new Guid("bb7bde8d-b9ce-4d68-a852-b16e621fa3a6"),
                            Amount = 2m
                        });
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", b =>
                {
                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessStepId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProcessStepId")
                        .IsUnique();

                    b.ToTable("ProcessStepTargets");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b95911b-3711-470a-84ff-f843825eb3e6"),
                            MachineId = new Guid("629893a3-3ae2-408f-8af5-70bcea9c1d19"),
                            Name = "Iron Ingot",
                            ProductionTime = 2m
                        },
                        new
                        {
                            Id = new Guid("34f401c1-1fbf-4d31-aff2-f04fa40f1831"),
                            MachineId = new Guid("9a874da3-3ea4-427d-8552-fc26dccba215"),
                            Name = "Iron Plate",
                            ProductionTime = 6m
                        });
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Corporation", "Corporation")
                        .WithMany("Branches")
                        .HasForeignKey("CorporationId");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ByProduct", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany("ByProducts")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.ProcessStep", "ProcessStep")
                        .WithMany("ImplementedMachinery")
                        .HasForeignKey("ProcessStepId");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MainProduct", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithOne("MainProduct")
                        .HasForeignKey("SatisfactorySmartHub.Domain.Entities.MainProduct", "RecipeId");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Branch", "Branch")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("BranchId");

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.Navigation("Branch");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.ProcessStep", "ProcessStep")
                        .WithOne("Target")
                        .HasForeignKey("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", "ProcessStepId");

                    b.Navigation("Item");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ProcessSteps");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Navigation("ImplementedMachinery");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("ByProducts");

                    b.Navigation("Ingredients");

                    b.Navigation("MainProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
