// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatisfactorySmartHub.Infrastructure.Persistance.Repositories;

#nullable disable

namespace SatisfactorySmartHub.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241025074629_AddItem")]
    partial class AddItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CorporationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ByProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ByProduct");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerConsumption")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ClockSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("MachineryConfigItem");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MainProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("MainProduct");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProcessStepId")
                        .IsUnique();

                    b.ToTable("ProcessStepTarget");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Corporation", "Corporation")
                        .WithMany("Branches")
                        .HasForeignKey("CorporationId");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ByProduct", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany("ByProducts")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MachineryConfigItem", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.ProcessStep", "ProcessStep")
                        .WithMany("ImplementedMachinery")
                        .HasForeignKey("ProcessStepId");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.MainProduct", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithOne("MainProduct")
                        .HasForeignKey("SatisfactorySmartHub.Domain.Entities.MainProduct", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Branch", "Branch")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("BranchId");

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.Navigation("Branch");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactorySmartHub.Domain.Entities.ProcessStep", "ProcessStep")
                        .WithOne("Target")
                        .HasForeignKey("SatisfactorySmartHub.Domain.Entities.ProcessStepTarget", "ProcessStepId");

                    b.Navigation("Item");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("SatisfactorySmartHub.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ProcessSteps");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Corporation", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.ProcessStep", b =>
                {
                    b.Navigation("ImplementedMachinery");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("SatisfactorySmartHub.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("ByProducts");

                    b.Navigation("Ingredients");

                    b.Navigation("MainProduct")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
